// ------------------------------------------------------------------
// Initial application state.
// This is the single source of truth for the default DAW project.
// Keep it deterministic — no random values — so undo/reset are reliable.
// ------------------------------------------------------------------

import {
  UI_THEME_DEFAULT,
  DEFAULT_PATTERN_COLOR,
} from "./constants";
import {
  makeSampleSettings,
  makePlaylistTracks,
  makeFxSlots,
  makeInsertSpectrum,
  makeInsertWaveform,
  makeMaximizerStereoMeter,
  makeEmptyPattern,
} from "./utils";

export const initialState = {
  transport: {
    bpm: 140,
    isPlaying: false,
    isRecording: false,
    mode: "pattern",
    songLoopEnabled: false,
    currentStep16: 0,
  },
  ui: {
    theme: UI_THEME_DEFAULT,
    browserTab: "packs",
    channelRackMode: "sequencer",
    patternClipboardIds: [],
    pianoRollScaleRoot: "C",
    pianoRollScaleType: "minor",
    fxEditorTarget: {
      insertId: "insert-1",
      slotId: "slot-1",
    },
    browserCollapsedFolders: {
      Packs: false,
      Plugins: false,
      "808 Mafia": false,
      "Nick Mira": true,
      Generators: false,
      Effects: true,
    },
    nextZ: 12,
    windows: {
      playlist: {
        open: true,
        z: 3,
        x: 0,
        y: 0,
        width: 960,
        height: 360,
        isMaximized: false,
        startMaximized: true,
        restoreRect: null,
      },
      channelRack: {
        open: true,
        z: 4,
        x: 350,
        y: 466,
        width: 800,
        height: 320,
        isMaximized: false,
        restoreRect: null,
      },
      pianoRoll: {
        open: false,
        z: 5,
        x: 420,
        y: 140,
        width: 760,
        height: 360,
        isMaximized: false,
        startMaximized: true,
        restoreRect: null,
      },
      mixer: {
        open: false,
        z: 6,
        x: 1170,
        y: 90,
        width: 650,
        height: 450,
        isMaximized: false,
        restoreRect: null,
      },
      fxPlugin: {
        open: false,
        z: 9,
        x: 980,
        y: 150,
        width: 540,
        height: 460,
        isMaximized: false,
        restoreRect: null,
      },
      sampleSettings: {
        open: false,
        z: 7,
        x: 910,
        y: 170,
        width: 560,
        height: 380,
        isMaximized: false,
        restoreRect: null,
      },
      patternList: {
        open: false,
        z: 8,
        x: 780,
        y: 140,
        width: 300,
        height: 440,
        isMaximized: false,
        restoreRect: null,
      },
      renderExport: {
        open: false,
        z: 10,
        x: 880,
        y: 120,
        width: 420,
        height: 340,
        isMaximized: false,
        restoreRect: null,
      },
    },
  },
  project: {
    activePatternId: "pat-1",
    activeChannelId: "ch-kick",
    channels: [
      {
        id: "ch-kick",
        name: "Kick",
        sampleRef: "",
        pluginRef: "",
        sampleSettings: makeSampleSettings(),
        muted: false,
        solo: false,
        volume: 1,
        pan: 0,
        inputMode: "steps",
        mixerInsertId: "insert-1",
      },
      {
        id: "ch-snare",
        name: "Snare",
        sampleRef: "",
        pluginRef: "",
        sampleSettings: makeSampleSettings(),
        muted: false,
        solo: false,
        volume: 1,
        pan: 0,
        inputMode: "steps",
        mixerInsertId: "insert-2",
      },
      {
        id: "ch-hat",
        name: "Hat",
        sampleRef: "",
        pluginRef: "",
        sampleSettings: makeSampleSettings(),
        muted: false,
        solo: false,
        volume: 1,
        pan: -0.15,
        inputMode: "piano",
        mixerInsertId: "insert-3",
      },
      {
        id: "ch-clap",
        name: "Clap",
        sampleRef: "",
        pluginRef: "",
        sampleSettings: makeSampleSettings(),
        muted: false,
        solo: false,
        volume: 1,
        pan: 0.08,
        inputMode: "steps",
        mixerInsertId: "insert-4",
      },
      {
        id: "ch-perc",
        name: "Perc",
        sampleRef: "",
        pluginRef: "",
        sampleSettings: makeSampleSettings(),
        muted: false,
        solo: false,
        volume: 1,
        pan: -0.08,
        inputMode: "steps",
        mixerInsertId: "insert-5",
      },
    ],
    patterns: [
      makeEmptyPattern({
        id: "pat-1",
        name: "Pattern 1",
        lengthSteps: 128,
        channels: [
          { id: "ch-kick" },
          { id: "ch-snare" },
          { id: "ch-hat" },
          { id: "ch-clap" },
          { id: "ch-perc" },
        ],
      }),
    ],
    playlistTracks: makePlaylistTracks(10),
    playlistClips: [],
  },
  mixer: {
    selectedInsertId: "insert-1",
    inserts: [
      {
        id: "master",
        name: "Master",
        isMaster: true,
        active: true,
        pan: 0,
        stereoSeparation: 0,
        fader: 1,
        meter: 0,
        meterSpectrum: makeInsertSpectrum(),
        meterWaveform: makeInsertWaveform(),
        maximizerReduction: 0,
        maximizerOutputDb: -96,
        maximizerStereoMeter: makeMaximizerStereoMeter(),
        routesTo: [],
        fxSlots: makeFxSlots(),
      },
      {
        id: "insert-1",
        name: "Insert 1",
        isMaster: false,
        active: true,
        pan: 0,
        stereoSeparation: 0,
        fader: 1,
        meter: 0,
        meterSpectrum: makeInsertSpectrum(),
        meterWaveform: makeInsertWaveform(),
        maximizerReduction: 0,
        maximizerOutputDb: -96,
        maximizerStereoMeter: makeMaximizerStereoMeter(),
        routesTo: ["master"],
        fxSlots: makeFxSlots(),
      },
      {
        id: "insert-2",
        name: "Insert 2",
        isMaster: false,
        active: true,
        pan: -0.08,
        stereoSeparation: -0.02,
        fader: 1,
        meter: 0,
        meterSpectrum: makeInsertSpectrum(),
        meterWaveform: makeInsertWaveform(),
        maximizerReduction: 0,
        maximizerOutputDb: -96,
        maximizerStereoMeter: makeMaximizerStereoMeter(),
        routesTo: ["master"],
        fxSlots: makeFxSlots(),
      },
      {
        id: "insert-3",
        name: "Insert 3",
        isMaster: false,
        active: true,
        pan: 0.11,
        stereoSeparation: 0.04,
        fader: 1,
        meter: 0,
        meterSpectrum: makeInsertSpectrum(),
        meterWaveform: makeInsertWaveform(),
        maximizerReduction: 0,
        maximizerOutputDb: -96,
        maximizerStereoMeter: makeMaximizerStereoMeter(),
        routesTo: ["master"],
        fxSlots: makeFxSlots(),
      },
      {
        id: "insert-4",
        name: "Insert 4",
        isMaster: false,
        active: true,
        pan: 0,
        stereoSeparation: 0,
        fader: 1,
        meter: 0,
        meterSpectrum: makeInsertSpectrum(),
        meterWaveform: makeInsertWaveform(),
        maximizerReduction: 0,
        maximizerOutputDb: -96,
        maximizerStereoMeter: makeMaximizerStereoMeter(),
        routesTo: ["master"],
        fxSlots: makeFxSlots(),
      },
      {
        id: "insert-5",
        name: "Insert 5",
        isMaster: false,
        active: true,
        pan: 0,
        stereoSeparation: 0,
        fader: 1,
        meter: 0,
        meterSpectrum: makeInsertSpectrum(),
        meterWaveform: makeInsertWaveform(),
        maximizerReduction: 0,
        maximizerOutputDb: -96,
        maximizerStereoMeter: makeMaximizerStereoMeter(),
        routesTo: ["master"],
        fxSlots: makeFxSlots(),
      },
    ],
  },
};
