import { usePianoRollKeyboardShortcuts } from "./usePianoRollKeyboardShortcuts";
import { usePianoRollClipboardActions } from "./usePianoRollClipboardActions";
import { usePianoRollMidiIo } from "./usePianoRollMidiIo";
import { usePianoRollMidiDrop } from "./usePianoRollMidiDrop";
import { usePianoRollGridMouseDown } from "./usePianoRollGridMouseDown";
import { usePianoRollNoteMouseDown } from "./usePianoRollNoteMouseDown";
import { usePianoRollVelocityEditing } from "./usePianoRollVelocityEditing";
import { usePianoRollNoteOps } from "./usePianoRollNoteOps";
import { usePianoRollScrollAndZoom } from "./usePianoRollScrollAndZoom";

export function usePianoRollInteractionHandlers(params) {
  const {
    activeChannel,
    activePattern,
    activePatternId,
    bpm,
    patternLength,
    editMode,
    stepWidth,
    rowHeight,
    gridWidth,
    gridHeight,
    pitchRows,
    snapStepSize,
    minNoteLength,
    selectedNoteIdSet,
    selectedNoteIds,
    selectedNotes,
    pianoNotes,
    scalePitchClasses,
    isSyncingScrollRef,
    isSyncingHorizontalScrollRef,
    gridWrapRef,
    keysRef,
    velocityWrapRef,
    midiImportInputRef,
    resizeSessionRef,
    dragSelectionRef,
    lastTouchedLengthRef,
    lastTouchedVelocityRef,
    setStepWidth,
    setSelectionBox,
    setSelectedNoteIds,
    setEditMode,
    dispatch,
    constants,
    utils,
    actions,
    externalFns,
  } = params;

  const { onGridWrapScroll, onVelocityWrapScroll, onKeysScroll, onGridWheel } =
    usePianoRollScrollAndZoom({
      gridWrapRef,
      keysRef,
      velocityWrapRef,
      isSyncingScrollRef,
      isSyncingHorizontalScrollRef,
      stepWidth,
      setStepWidth,
      minStepWidth: constants.minStepWidth,
      maxStepWidth: constants.maxStepWidth,
      clampFn: utils.clampFn,
    });

  const { getGridPointerFromEvent, removeNote, ensureNoteIsPiano } =
    usePianoRollNoteOps({
      gridWrapRef,
      gridHeaderHeight: constants.gridHeaderHeight,
      activeChannel,
      dispatch,
      activePatternId,
      defaultNoteVelocity: constants.defaultNoteVelocity,
      clampFn: utils.clampFn,
      makeIdFn: utils.makeGeneratedNoteIdFn,
      toggleStepAction: actions.toggleStepAction,
      togglePianoNoteAction: actions.togglePianoNoteAction,
    });

  const {
    velocityBrushActiveRef,
    velocityLaneHeight,
    velocityReadout,
    isVelocityLaneHovered,
    isVelocityEditing,
    setIsVelocityLaneHovered,
    setVelocityReadout,
    onVelocityResizeMouseDown,
    startVelocityBrush,
    onVelocityBarMouseDown,
  } = usePianoRollVelocityEditing({
    activeChannel,
    dispatch,
    activePatternId,
    velocityWrapRef,
    selectedNotes,
    pianoNotes,
    stepWidth,
    patternLength,
    defaultNoteVelocity: constants.defaultNoteVelocity,
    minVelocityLaneHeight: constants.minVelocityLaneHeight,
    maxVelocityLaneHeight: constants.maxVelocityLaneHeight,
    clampFn: utils.clampFn,
    midiVelocityToPercentFn: utils.midiVelocityToPercentFn,
    percentToMidiVelocityFn: utils.percentToMidiVelocityFn,
    ensureNoteIsPiano,
    lastTouchedVelocityRef,
    setPianoNoteVelocityAction: actions.setPianoNoteVelocityAction,
    getSelectionId: utils.getSelectionId,
  });

  const {
    copySelectedNotes,
    deleteSelectedNotes,
    cutSelectedNotes,
    pasteClipboardNotes,
  } = usePianoRollClipboardActions({
    selectedNotes,
    activePatternId,
    activePattern,
    activeChannel,
    dispatch,
    patternLength,
    minFreeLength: constants.minFreeLength,
    pitchMin: constants.pitchMin,
    pitchMax: constants.pitchMax,
    defaultVelocity: constants.defaultNoteVelocity,
    clampFn: utils.clampFn,
    makeIdFn: utils.makeGeneratedNoteIdFn,
    addPianoNotesBatchAction: actions.addPianoNotesBatchAction,
    removePianoNotesBatchAction: actions.removePianoNotesBatchAction,
    setSelectedNoteIds,
    setEditMode,
  });

  usePianoRollKeyboardShortcuts({
    activeChannel,
    patternId: activePatternId,
    channelId: activeChannel?.id || "",
    editMode,
    pianoNotes,
    selectedNotes,
    scalePitchClasses,
    pitchMin: constants.pitchMin,
    pitchMax: constants.pitchMax,
    setEditMode,
    setSelectedNoteIds,
    toSelectionId: utils.getSelectionId,
    copySelectedNotes,
    cutSelectedNotes,
    pasteClipboardNotes,
    deleteSelectedNotes,
    ensureNoteIsPiano,
    clampFn: utils.clampFn,
    moveByScaleStepFn: utils.moveByScaleStepFn,
    onMoveSelectedNotes: function ({ patternId, channelId, moves }) {
      dispatch(
        actions.movePianoNotesBatchAction({
          patternId,
          channelId,
          moves,
        }),
      );
    },
  });

  const { onGridMouseDown } = usePianoRollGridMouseDown({
    activeChannel,
    activePattern,
    activePatternId,
    editMode,
    patternLength,
    stepWidth,
    rowHeight,
    gridWidth,
    gridHeight,
    pitchRows,
    snapStepSize,
    minNoteLength,
    minFreeLength: constants.minFreeLength,
    pitchMax: constants.pitchMax,
    c5Pitch: constants.c5Pitch,
    marqueeMinDrag: constants.marqueeMinDrag,
    pianoNotes,
    dispatch,
    getGridPointerFromEvent,
    setSelectionBox,
    setSelectedNoteIds,
    toggleStepAction: actions.toggleStepAction,
    togglePianoNoteAction: actions.togglePianoNoteAction,
    startPreviewNote: externalFns.startPreviewNote,
    lastTouchedLengthRef,
    lastTouchedVelocityRef,
    clampFn: utils.clampFn,
    isNearlyEqualFn: utils.isNearlyEqualFn,
    quantizeBySnapFn: utils.quantizeBySnapFn,
    getSelectionId: utils.getSelectionId,
  });

  const { onPianoRollMidiDragOver, onPianoRollMidiDrop } = usePianoRollMidiDrop(
    {
      activePattern,
      activeChannel,
      activePatternId,
      patternLength,
      stepWidth,
      dispatch,
      clampFn: utils.clampFn,
      getGridPointerFromEvent,
      pasteMidiPatternToChannelAction: actions.pasteMidiPatternToChannelAction,
      dataTransferHasMidiPatternPayloadFn:
        externalFns.dataTransferHasMidiPatternPayloadFn,
      dataTransferHasMidiFilePayloadFn: externalFns.dataTransferHasMidiFilePayloadFn,
      readMidiPatternFromDataTransferFn: externalFns.readMidiPatternFromDataTransferFn,
      readMidiFilePayloadFromDataTransferFn:
        externalFns.readMidiFilePayloadFromDataTransferFn,
      parseMidiArrayBufferToStepNotesFn: externalFns.parseMidiArrayBufferToStepNotesFn,
      isMidiFileNameFn: externalFns.isMidiFileNameFn,
    },
  );

  const { onExportMidiClick, onImportMidiClick, onImportMidiFileChange } =
    usePianoRollMidiIo({
      midiImportInputRef,
      activePattern,
      activeChannel,
      activePatternId,
      bpm,
      dispatch,
      isMidiFileNameFn: externalFns.isMidiFileNameFn,
      parseMidiArrayBufferToStepNotesFn: externalFns.parseMidiArrayBufferToStepNotesFn,
      extractMidiPatternNotesFn: externalFns.extractMidiPatternNotesFn,
      triggerMidiDownloadFn: externalFns.triggerMidiDownloadFn,
      pasteMidiPatternToChannelAction: actions.pasteMidiPatternToChannelAction,
    });

  const { onNoteMouseDown } = usePianoRollNoteMouseDown({
    activeChannel,
    activePatternId,
    editMode,
    selectedNoteIdSet,
    selectedNoteIds,
    selectedNotes,
    pianoNotes,
    patternLength,
    stepWidth,
    rowHeight,
    snapStepSize,
    minNoteLength,
    minFreeLength: constants.minFreeLength,
    snapEpsilon: constants.snapEpsilon,
    pitchMin: constants.pitchMin,
    pitchMax: constants.pitchMax,
    defaultNoteVelocity: constants.defaultNoteVelocity,
    dispatch,
    clampFn: utils.clampFn,
    isNearlyEqualFn: utils.isNearlyEqualFn,
    quantizeBySnapFn: utils.quantizeBySnapFn,
    getSelectionId: utils.getSelectionId,
    ensureNoteIsPiano,
    removeNote,
    deleteSelectedNotes,
    setSelectedNoteIds,
    movePianoNotesBatchAction: actions.movePianoNotesBatchAction,
    movePianoNoteAction: actions.movePianoNoteAction,
    setPianoNoteLengthAction: actions.setPianoNoteLengthAction,
    toggleStepAction: actions.toggleStepAction,
    togglePianoNoteAction: actions.togglePianoNoteAction,
    resizeSessionRef,
    dragSelectionRef,
    startPreviewNote: externalFns.startPreviewNote,
    lastTouchedLengthRef,
    lastTouchedVelocityRef,
    setVelocityReadout,
    midiVelocityToPercentFn: utils.midiVelocityToPercentFn,
  });

  return {
    onGridWrapScroll,
    onVelocityWrapScroll,
    onKeysScroll,
    onGridWheel,
    velocityBrushActiveRef,
    velocityLaneHeight,
    velocityReadout,
    isVelocityLaneHovered,
    isVelocityEditing,
    setIsVelocityLaneHovered,
    onVelocityResizeMouseDown,
    startVelocityBrush,
    onVelocityBarMouseDown,
    onGridMouseDown,
    onPianoRollMidiDragOver,
    onPianoRollMidiDrop,
    onExportMidiClick,
    onImportMidiClick,
    onImportMidiFileChange,
    onNoteMouseDown,
  };
}
